export enum BookingState {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_RESERVATION = 'PENDING_RESERVATION',
  RESERVATION_IN_PROGRESS = 'RESERVATION_IN_PROGRESS',
  CONFIRMED = 'CONFIRMED',
  CANCELLATION_IN_PROGRESS = 'CANCELLATION_IN_PROGRESS',
  CANCELLED = 'CANCELLED'
}
